name: Auto Label Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const issue = context.payload.issue

            const labelsToAdd = []
            const labelConditions = [
            {label: 'bug-report', keywords: ['Bug', 'bug']},
            {label: 'enhancement', keywords: ['suggestion', 'enhancement', 'feature request', 'Feature request', 'Feature Request', 'advice']},
            {label: 'documentation', keywords: ['docs', 'documentation', 'Wiki', 'wiki']}
            ]
            // Add tags based on conditions
            for (const {label, keywords} of labelConditions) {
                for (const keyword of keywords) {
                    if (issue.title.includes(keyword)) {
                        labelsToAdd.push(label)
                        break
                    }
                }
            }
            if (labelsToAdd.length == 0) {
                labelsToAdd.push('needs-information')
            }

            console.log("All of tags: " , labelsToAdd)

            // Add tags
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: labelsToAdd
            })
          github-token: ${{ secrets.GH_TOKEN }}
  assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Add assignees
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const reviewers = ['acheong08'];
            const reviewer = reviewers[Math.floor(Math.random() * reviewers.length)];

            // Add assignees
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: reviewer
            })
          github-token: ${{ secrets.GH_TOKEN }}
