name: Close inactive issues
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close inactive issues
        uses: actions/stale@v8
        with:
          days-before-issue-stale: 2
          days-before-issue-close: 3
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 2 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 3 days since being marked as stale."
          stale-pr-label: "stale"
          days-before-pr-stale: 25
          days-before-pr-close: 30
          stale-pr-message: "This issue is stale because it has been open for 5 days with no activity."
          close-pr-message: "This issue was closed because it has been inactive for 30 days since being marked as stale."
      - name: Lock Threads
        uses: dessant/lock-threads@v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: '90'
          process-only: 'issues'
          log-output: true
